[package]
name = "qoitest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image.workspace = true
qoi = "0.4.1"
rayon = "1.8.0"
types = { workspace = true }
